apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtqs-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dtqs-api
  template:
    metadata:
      labels:
        app: dtqs-api
    spec:
      containers:
        - name: dtqs-api
#          image: repo/dtqs_api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
#              value: "postgres://"
            - name: RABBITMQ_URL
#              value: "amqp://rabbitmq"
